### ISSUE TITLE
How to use uaaldapimport tools import ldap user to pivotal?

### ISSUE THREAD

**Issue by alandchen** [pivotalservices/uaaldapimport#3]
(1):E:\SetupFile\ruby-2.2.4-x64\ruby-2.2.4-x64-mingw32\bin\uaac target https://uaa.system.lmpivotal.com
(2):E:\SetupFile\ruby-2.2.4-x64\ruby-2.2.4-x64-mingw32\bin\uaac token client get admin -s SSSSSS
(3):E:\SetupFile\ruby-2.2.4-x64\ruby-2.2.4-x64-mingw32\bin\uaac client add -i

(4):Client name: aland.chen
New client secret:
Verify new client secret:
scope (list): Press Enter
authorized grant types (list): client_credentials
authorities (list): cloud_controller.admin,scim.write
access token validity (seconds): Press Enter
refresh token validity (seconds): Press Enter
redirect uri (list): Press Enter
autoapprove (list): Press Enter
signup redirect url (url): Press Enter

(5):users.yml  file
users:
- uid: aland.chen@XXXXX
  externalid: uid=aland.chen,OU=China,DC=XXX,DC=com,DC=cn
  emails:
  - aland.chen@XXXXX
  orgs:
    - name: system 
      roles:
      - OrgManager
      spaces:
        - name: apps-manager
          roles:
          - SpaceManager
          
          
(6):environment.yml file
uaaurl: https://uaa.system.lmpivotal.com
ccurl: https://api.system.lmpivotal.com
clientid: aland.chen
secret: SSSSS

(7):C:\go\src\github.com\pivotalservices\uaaldapimport 的目录

016/06/02  14:39    <DIR>          .
016/06/02  14:39    <DIR>          ..
015/08/31  12:02                25 .gitignore
016/06/01  14:08    <DIR>          adduser
015/08/31  12:02               678 checkHash
016/06/01  14:08    <DIR>          cloudcontroller
016/06/01  14:08    <DIR>          config
016/06/02  14:19               120 environment.yml
016/06/02  13:48               126 environment.yml.bak
016/06/01  14:08    <DIR>          functions
016/06/01  14:08    <DIR>          Godeps
015/08/31  12:02             1,309 main.go
015/08/31  12:02             3,131 README.md
015/08/31  12:02                97 runlocalbuild
015/08/31  12:02               368 setReleaseName
016/06/01  14:08    <DIR>          token
016/06/02  12:26         8,833,024 uaaldapimport.exe
016/06/01  12:01            68,150 uaausersimport
016/06/02  14:39               306 users.yml
016/06/02  13:54               285 users.yml.bak
015/08/31  12:02             1,917 wercker.yml
             13 个文件      8,909,536 字节
              8 个目录 15,370,903,552 可用字节

:\go\src\github.com\pivotalservices\uaaldapimport>uaaldapimport.exe

But I can't login:  https://console.XXXXX.com

who can help me? Tell how to  integrates cf with ldap?

**Comment by datianshi** [comment]
This tool is simply to load users.
You need to configure your cf env with appropriate ldap integration

If you are using pivotal cf -> https://docs.pivotal.io/pivotalcf/1-7/opsguide/auth-sso.html#configure-ldap

If you are using bosh managed deployment -> https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L493

About UAA + Ldap -> https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md

Good luck @alandchen

**Comment by alandchen** [comment]
Dear ,
   Yes , I have config it. When I config the uaa.yml<https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/uaa.yml>  on uaa server,  then restart the uaa server , all config has resotre, why?

  Anther issue,  can’t   click  the apply change.
   [cid:image002.png@01D1BCF2.98A78D00]


[cid:image001.png@01D1BCF2.614AE1E0]

发件人: Shaozhen Ding [mailto:notifications@github.com]
发送时间: 2016年6月2日 16:48
收件人: pivotalservices/uaaldapimport
抄送: Chen, Aland; Mention
主题: Re: [pivotalservices/uaaldapimport] How to use uaaldapimport tools import ldap user to pivotal? (#3)


This tool is simply to load users.
You need to configure your cf env with appropriate ldap integration

If you are using pivotal cf -> https://docs.pivotal.io/pivotalcf/1-7/opsguide/auth-sso.html#configure-ldap

If you are using bosh managed deployment -> https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L493

About UAA + Ldap -> https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md

Good luck @alandchen<https://github.com/alandchen>

**Comment by datianshi** [comment]
Are you using PCF?

You should use ops manager instead of changing uaa.yml directly

can’t click the apply change, PCF issue

You seems having an issue with PCF/CF/UAA integration with ldap, while it
is not related to this tool. Can you file a support ticket or submit issues
in UAA side?

**Comment by alandchen** [comment]
Dear,
Yes, I’m PCF 1.6.2.
Use ops manager instead of changing uaa.yml? How to operations it ?
Thanks for your support.

发件人: Shaozhen Ding [mailto:notifications@github.com]
发送时间: 2016年6月2日 17:23
收件人: pivotalservices/uaaldapimport
抄送: Chen, Aland; Mention
主题: Re: [pivotalservices/uaaldapimport] How to use uaaldapimport tools import ldap user to pivotal? (#3)

Are you using PCF?

You should use ops manager instead of changing uaa.yml directly

can’t click the apply change, PCF issue

You seems having an issue with PCF/CF/UAA integration with ldap, while it
is not related to this tool. Can you file a support ticket or submit issues
in UAA side?

**Comment by datianshi** [comment]
@alandchen 

https://docs.pivotal.io/pivotalcf/1-7/opsguide/auth-sso.html#configure-ldap

**Comment by datianshi** [comment]
Close the issue, since this is a PCF + LDAP issue, not tool related
